(******************************************************************************)
(*                                                                            *)
(*                      ROME STATUTE OF THE ICC (1998)                        *)
(*                                                                            *)
(*     International Criminal Court jurisdiction: genocide, crimes against    *)
(*     humanity, war crimes, crime of aggression. Elements of crimes,         *)
(*     complementarity principle, and admissibility criteria.                 *)
(*                                                                            *)
(*     "The most serious crimes of concern to the international community     *)
(*      as a whole must not go unpunished."                                   *)
(*     - Preamble, Rome Statute                                               *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 6, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
